### ISSUE TITLE
More inspiration - tildeio/simple-html-tokenizer

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/snapdragon#3]
Just browsing some tokenizers/parsers around. This one can be inspiration and is well and logically structured, imho. https://github.com/tildeio/simple-html-tokenizer/blob/master/lib/simple-html-tokenizer/evented-tokenizer.js :)

**Comment by jonschlinkert** [comment]
closing, thanks for the link, but it's a bit verbose for what it accomplishes. I think we can do something similar but simpler here.
