### ISSUE TITLE
[readme] - explain more for new-comers

### ISSUE THREAD

**Issue by revelt** [jonschlinkert/snapdragon#5]
Current iteration of Readme doesn't tell what exactly does snapdragon do.

It is stated it is "a factory", but there's no link to explanation what "a factory" is.

I wrote a few libraries that work with parsed HTML AST's and I'm somewhat familiar with the subject, yet I find the Readme file too steep and unfriendly.

Here are the simple questions that are still unanswered by the current Readme:

* What does this library _achieve_ by compiling and parsing?
* Does snapdragon work on HTML (parsed or raw strings)? Or external CSS file's (parsed or raw string)?
* How does snapdragon compare to, let's say a combination of [PostHTML-parser](https://github.com/posthtml/posthtml-parser) and [PostHTML-render](https://github.com/posthtml/posthtml-render)? Can all be used together?

If you would lower the barrier for new-comers you would attract more contributors and win promoters for this library.

**Comment by jonschlinkert** [comment]
great advice! thanks! I've been [working on docs](https://github.com/jonschlinkert/snapdragon/tree/master/docs), this really helps me know what to focus on.

**Comment by jonschlinkert** [comment]
> I wrote a few libraries that work with parsed HTML AST's

any links you can share so I can get some ideas for the docs by way of example?

**Comment by revelt** [comment]
Well, my libraries (and their documentation) are too humble to compare with `snapdragon`: HTML AST [getter/setter](https://github.com/code-and-send/posthtml-ast-get-object) (querying by object), another [getter/setter](https://github.com/code-and-send/posthtml-ast-get-values-by-key) to query by key/value/both, also libraries to delete by [key](https://github.com/code-and-send/posthtml-ast-delete-key) or [object](https://github.com/code-and-send/posthtml-ast-delete-object), also to [compare](https://github.com/code-and-send/posthtml-ast-compare) AST trees or branches and [few](https://github.com/code-and-send/object-set-all-values-to) [auxiliary](https://github.com/code-and-send/util-nonempty) [ones](https://github.com/code-and-send/object-merge-advanced).

By the way, I had to write my own dom-manipulation libraries because [DomUtils](https://github.com/fb55/DomUtils) has no documentation at all. I found [htmlparser2](https://github.com/fb55/htmlparser2) documentation not friendly and switched to its dependency, [PostHTML-parser](https://github.com/posthtml/posthtml-parser) which did a better job explaining how to use it than its parent.

It would be handy if `snapdragon` Readme explained more, at the basic level, where it stands in the big picture of parsing and working with AST's of various kinds. As I mentioned in the first post, what is `factory` and how does it tie with html/css AST operations?

**Comment by jonschlinkert** [comment]
thanks for the detail. 

> I found htmlparser2 documentation not friendly

I know exactly what you mean. I was initially going to create a snapdragon plugin for htmlparser2, but it was extremely difficult to do even the simplest thing with it. 

> what is factory and how does it tie with html/css AST operations?

Per my comment about htmlparser2, I created [snapdragon-cheerio](https://github.com/jonschlinkert/snapdragon-cheerio) to convert the cheerio AST into a snapdragon-compatible AST. While I'm working on docs, maybe this will help by way of example in the meantime. 

Also, I used snapdragon in the following projects

- https://github.com/jonschlinkert/micromatch (see the dev branch)
- https://github.com/jonschlinkert/braces
- https://github.com/jonschlinkert/expand-brackets
- https://github.com/jonschlinkert/nanomatch

and I'm about to release a project that will probably explain best what snapdragon is capable of :)

**Comment by tunnckoCore** [comment]
Can't get what's the problem to understand what `factory` means. It means that `snapdragon` is "framework" for creating parsers/compilers/renders, based on a regex approach. Meaning that you give a string (no matter what - css, html, json, etc) and then you use/set different "plugins/sets" how to parse each character in that string. Basically it just loops over the given characters, based on the given regex from that exactly plugins.

In reality, you even can implement html parser with `snapdragon` or `json` parser or `css`-ish parser (for sass/less/scss/etc). Think of it just as "defining grammer for usual parser/compiler" - for example you should define a grammer for the [nearley](https://github.com/Hardmath123/nearley), for [PEG.js](https://pegjs.org/) too)

I already played few times with Snapdragon, but it can be quite too complex for some cases, or at least for me (maybe not enough playing ;p)

**offtopic:** btw good article to read: https://medium.com/@gajus/parsing-absolutely-anything-in-javascript-using-earley-algorithm-886edcc31e5e#.szsnx4tow

> about to release a project

hmmmm :eagle: :ear:

**Comment by jonschlinkert** [comment]
> but it can be quite too complex for some cases

yeah, parsing/compiling can certainly get complex. IMHO, https://github.com/jonschlinkert/braces is an example of a pretty complex implementation. 

> Think of it just as "defining grammer for usual parser/compiler"

this made me think of a point of differentiation for snapdragon. you could actually use snapdragon to create something like nearly or PEG.js. You don't need to learn a new language/grammar to use snapdragon, you only need to know how to use regex.

**Comment by tunnckoCore** [comment]
@jonschlinkert yea, exactly what I meant :)

**Comment by jonschlinkert** [comment]
Done. I've improved the readme quite a bit. Please let me know if you agree, and if so you can close. Thanks!

> I'm about to release a project that will probably explain best what snapdragon is capable of :)

[This is the project](http://breakdance.io) I was referring to.

**Comment by revelt** [comment]
Good stuff, let's close.
