### ISSUE TITLE
Please tag release release 0.11.0, which is the only release that isn't tagged and you usually tag all releases

### ISSUE THREAD

**Issue by SnarkBoojum** [jonschlinkert/snapdragon#9]
According to github, the last release was 0.8.0... but there are commits saying otherwise : perhaps you forgot to tag them?

Thanks!

**Comment by simevo** [comment]
In npm registry it says the current version is **0.11.0**, but there is no such tag here. Please tag the latest release. Thanks, Paolo

**Comment by jonschlinkert** [comment]
![image](https://user-images.githubusercontent.com/383994/33432287-698d252a-d5a5-11e7-9261-ce1a701c7ce9.png)

**Comment by jonschlinkert** [comment]
I should have looked more closely (as should you I suppose). When I tried to create a tag for 0.11.0 I was given an error message informing me that 0.11.0 already existed.

**Comment by SnarkBoojum** [comment]
Oh, dear... In fact, the problem is that both github and uscan (the tool we use to detect new versions) see 0.8* as much more recent than 0.1* -- so I didn't see that release anywhere I looked... I'll try to force the use of two digits for the minor part of the version. That will make 0.?.* disappear, but at least the remaining seen ones will include what we want!

Thanks!

**Comment by SnarkBoojum** [comment]
Nope... that doesn't work since github shows those new versions only on the second page...
